/* eslint-disable */
var data1 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"1",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#9e5fff33",
  "dragBgColor":"#9e5fff",
  "borderColor":"#9e5fff",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor":true,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};
var data2 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"2",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#00a9ff33",
  "dragBgColor":"#00a9ff",
  "borderColor":"#00a9ff",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor": false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};

var data3 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"3",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#ff558333",
  "dragBgColor":"#ff5583",
  "borderColor":"#ff5583",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor":false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};
var goingComingData1 = {
  "id":"75e590d1-ce31-5c67-aec4-90dd090c8115",
  "calendarId":"1",
  "title":"Tohbiz vepa wicpab.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-24T09:00:00.000Z",
  "end":"2019-07-24T13:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#9e5fff33",
  "dragBgColor":"#9e5fff",
  "borderColor":"#9e5fff",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":44,
  "comingDuration":101,
  "recurrenceRule":"",
  "raw":{
    "memo":"Fed hifwi otulumbal afe sem zahmulo miwvoko couldor hik tacigava me duvasof.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Marvin Rios",
      "avatar":"//www.gravatar.com/avatar/a03da689dcea6af2ed396021dd39826d",
      "company":"Spherion Corp",
      "email":"kus@te.lc",
      "phone":"(885) 451-3012"
    },
    "isMajor":true,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1084 Opoub Loop",
  "attendees":[
    "Russell Oliver",
    "Timothy Graves",
    "Benjamin Spencer",
    "Evan Riley",
    "Christine Richardson",
    "Christina Peterson",
    "Herbert Carson"
  ],
  "customStyle": "left:0"
};
var goingComingData2 = {
  "id":"75e590d1-ce31-5c67-aec4-90dd090c8115",
  "calendarId":"2",
  "title":"Tohbiz vepa wicpab.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-24T09:00:00.000Z",
  "end":"2019-07-24T13:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#00a9ff33",
  "dragBgColor":"#00a9ff",
  "borderColor":"#00a9ff",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":44,
  "comingDuration":101,
  "recurrenceRule":"",
  "raw":{
    "memo":"Fed hifwi otulumbal afe sem zahmulo miwvoko couldor hik tacigava me duvasof.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Marvin Rios",
      "avatar":"//www.gravatar.com/avatar/a03da689dcea6af2ed396021dd39826d",
      "company":"Spherion Corp",
      "email":"kus@te.lc",
      "phone":"(885) 451-3012"
    },
    "isMajor":false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1084 Opoub Loop",
  "attendees":[
    "Russell Oliver",
    "Timothy Graves",
    "Benjamin Spencer",
    "Evan Riley",
    "Christine Richardson",
    "Christina Peterson",
    "Herbert Carson"
  ]
};

var data2_1 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd1",
  "calendarId":"1",
  "title":"꼽사리",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T18:00:00.000Z",
  "end":"2019-07-21T20:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#9e5fff33",
  "dragBgColor":"#9e5fff",
  "borderColor":"#9e5fff",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor":false
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"]
};


var data4 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"4",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#03bd9e33",
  "dragBgColor":"#03bd9e",
  "borderColor":"#03bd9e",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor":false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};
var data5 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"5",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#bbdc0033",
  "dragBgColor":"#bbdc00",
  "borderColor":"#bbdc00",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor": false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};

var data6 = {
  "id":"a9c8aa27-2085-5a50-ad4c-832ec8f272bd",
  "calendarId":"6",
  "title":"Vihev ivani nutefhag.",
  "body":"",
  "isAllday":false,
  "start":"2019-07-21T19:00:00.000Z",
  "end":"2019-07-21T21:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#9d9d9d33",
  "dragBgColor":"#9d9d9d",
  "borderColor":"#9d9d9d",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":0,
  "comingDuration":0,
  "recurrenceRule":"repeated events",
  "raw":{
    "memo":"Vepweb jap wuhivag liribe uvatusi nerav evu ocalet mav vokesvus didajib cabev zerhowup.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Isabel Lyons",
      "avatar":"//www.gravatar.com/avatar/2dd3c16562edb9ef7734c380f6380fcd",
      "company":"Hughes Supply Inc.",
      "email":"ziifeho@fialu.ht",
      "phone":"(887) 567-2526"
    },
    "isMajor":false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1944 Riri Extension",
  "attendees":["Daniel Bowman","Bettie Medina","Mattie Garcia","Jesse Watts"],
  "customStyle": "left:0"
};

var goingComingData3 = {
  "id":"75e590d1-ce31-5c67-aec4-90dd090c81156",
  "calendarId":"3",
  "title":"똑같은 시간 중복 일정",
  "body":"",
  "isAllday":false,
  "start":"2019-07-24T09:00:00.000Z",
  "end":"2019-07-24T13:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#ffbb3b33",
  "dragBgColor":"#ffbb3b",
  "borderColor":"#ffbb3b",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":44,
  "comingDuration":101,
  "recurrenceRule":"",
  "raw":{
    "memo":"Fed hifwi otulumbal afe sem zahmulo miwvoko couldor hik tacigava me duvasof.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Marvin Rios",
      "avatar":"//www.gravatar.com/avatar/a03da689dcea6af2ed396021dd39826d",
      "company":"Spherion Corp",
      "email":"kus@te.lc",
      "phone":"(885) 451-3012"
    },
    "isMajor":true,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1084 Opoub Loop",
  "attendees":[
    "Russell Oliver",
    "Timothy Graves",
    "Benjamin Spencer",
    "Evan Riley",
    "Christine Richardson",
    "Christina Peterson",
    "Herbert Carson"
  ],
  "customStyle": "left:0"
};
var goingComingData4 = {
  "id":"75e590d1-ce31-5c67-aec4-90dd090c81156",
  "calendarId":"4",
  "title":"똑같은 시간 중복 일정",
  "body":"",
  "isAllday":false,
  "start":"2019-07-24T09:00:00.000Z",
  "end":"2019-07-24T13:00:00.000Z",
  "category":"time",
  "dueDateClass":"",
  "color":"#000000",
  "bgColor":"#ff558333",
  "dragBgColor":"#ff5583",
  "borderColor":"#ff5583",
  "customStyle":"",
  "isFocused":false,
  "isPending":false,
  "isVisible":true,
  "isReadOnly":false,
  "goingDuration":44,
  "comingDuration":101,
  "recurrenceRule":"",
  "raw":{
    "memo":"Fed hifwi otulumbal afe sem zahmulo miwvoko couldor hik tacigava me duvasof.",
    "hasToOrCc":false,
    "hasRecurrenceRule":false,
    "location":null,
    "class":"public",
    "creator":{
      "name":"Marvin Rios",
      "avatar":"//www.gravatar.com/avatar/a03da689dcea6af2ed396021dd39826d",
      "company":"Spherion Corp",
      "email":"kus@te.lc",
      "phone":"(885) 451-3012"
    },
    "isMajor":false,
    "isDuplicate": true
  },
  "isPrivate":false,
  "location":"1084 Opoub Loop",
  "attendees":[
    "Russell Oliver",
    "Timothy Graves",
    "Benjamin Spencer",
    "Evan Riley",
    "Christine Richardson",
    "Christina Peterson",
    "Herbert Carson"
  ]
};
